# Blog settings
#permalink: /blog/:title


# My variables
name: So!Much!Stuff!
description: A Jekyll Theme
google_verification: null

baseurl: "/blog"
url: "blue-grey.github.io"

# File management
include: [".htaccess"]
#exclude: ["README.md", "LICENSE"]


# Sass
sass:
  style: :compressed
  sass_dir: _sass


# Markdown
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
highlighter: rouge
